version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-FileCopyrightText = "SYS, Supporting Your Systems B.V."
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = [
    "*.md",
    "docs/**"
]
SPDX-FileCopyrightText = "SYS, Supporting Your Systems B.V."
SPDX-License-Identifier = "CC-BY-SA-4.0"
