server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:postgresql://postgres:5432/hapi_notifiedpull_stu3'
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    fhir_version: DSTU3
    tester:
      home:
        id: home
        name: hapi STU3 Tester (8082 for notified pull)
        server_address: 'http://localhost:8082/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: DSTU3
    validation:
      requests_enabled: false
      responses_enabled: false
    allow_external_references: true
    allow_multiple_delete: true
    allow_expunge: true
    delete_expunge_enabled: true
    allow_cascading_deletes: true
